# Copyright (c) HashiCorp, Inc.
# SPDX-License-Identifier: MPL-2.0

packages:
  - "packages/*"
  - "packages/@cdktn/*"
  - "examples/**"
  - "tools/generate-function-bindings"

overrides:
  "@types/react": 18.3.28
  jsii: 5.9.37

onlyBuiltDependencies:
  - esbuild
  - nx
  - unrs-resolver
